DROP DATABASE IF EXISTS 'FunFacts';
DROP DATABASE IF EXISTS 'fun_facts';
CREATE DATABASE 'fun_facts'
    DEFAULT CHARACTER SET UTF8
    DEFAULT COLLATE utf8_general_ci;

USE 'mysql';
GRANT ALL PRIVILEGES  ON fun_facts.* TO 'joseph'@'localhost' IDENTIFIED BY ''

WITH GRANT OPTION;
FLUSH PRIVILEGES;