# Generated by Django 4.2.1 on 2023-06-07 05:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fact_title', models.CharField(max_length=128, null=True)),
                ('fact_text', models.CharField(max_length=500)),
                ('fact_discription', models.TextField(null=True)),
                ('source', models.CharField(max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('bio', models.TextField()),
                ('profile_picture', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='facts.user')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('preferences', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facts.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateTimeField()),
                ('activity_type', models.CharField(max_length=20)),
                ('activity_details', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField()),
                ('date_rated', models.DateTimeField(auto_now_add=True)),
                ('fact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.facts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('fact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.facts')),
            ],
        ),
        migrations.CreateModel(
            name='FactCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.categories')),
                ('fact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.facts')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('date_commented', models.DateTimeField(auto_now_add=True, null=True)),
                ('fact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.facts')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.user')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='facts',
            field=models.ManyToManyField(related_name='categories', to='facts.facts'),
        ),
    ]
