# Generated by Django 4.2.1 on 2023-06-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_alter_facts_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
