# Generated by Django 4.2.1 on 2023-06-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_alter_categories_options_alter_categories_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
